#ifndef CPOLYGON_ORIENTATION_H
#define CPOLYGON_ORIENTATION_H

enum CPolygonOrientation {
  CPOLYGON_ORIENTATION_UNKNOWN          =  0,
  CPOLYGON_ORIENTATION_CLOCKWISE        = -1,
  CPOLYGON_ORIENTATION_ANTICLOCKWISE    =  1,
  CPOLYGON_ORIENTATION_COUNTERCLOCKWISE = CPOLYGON_ORIENTATION_ANTICLOCKWISE
};

#endif
